baseURL = "https://natluenthaisong.github.io/randomthoughts/"
languageCode = 'en-us'
title = 'Random Thoughts'
theme = "hugo-paper"
[params]
  defaultTheme = "light"
  subtitle = "Where thoughts connect and life unfolds."
[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"
[markup.goldmark.renderer]
  unsafe = true