baseURL = "https://natluenthaisong.github.io/randomthoughts/"
languageCode = 'en-us'
title = 'Random Thoughts'
theme = "hugo-paper"
[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"